import type { Playbook } from "@/types/playbook";

export const MOCK_PLAYBOOK: Playbook = {
  summary:
    "A six-phase rollout that captures break-even by Q2 by piloting on the highest-friction workflow first, then scaling once productivity gains are measured.",
  successMetrics: [
    "Manual hours reclaimed per week per team member",
    "Error rate reduction on automated workflows",
    "Time from request to delivery on the target workflow",
    "User adoption rate across the affected team",
  ],
  topRisks: [
    "Underestimating change-management effort",
    "LLM output quality drift without monitoring",
    "Stakeholder fatigue if pilot results aren't communicated weekly",
  ],
  phases: [
    {
      id: "p1",
      timeframe: "Week 1",
      title: "Identify the bottleneck",
      objective: "Pick the single workflow where AI will produce the most measurable value.",
      actions: [
        "Shadow team members for 2 days; log time spent per task",
        "Rank tasks by manual hours × frequency × error rate",
        "Pick one workflow with high volume and clear input/output",
        "Set baseline metrics (hours per week, errors per month)",
      ],
      deliverable: "One-page bottleneck brief with measured baseline",
      estCost: 4000,
      owner: "Ops Lead",
      risks: ["Picking a low-volume task that won't move the ROI needle"],
    },
    {
      id: "p2",
      timeframe: "Week 2",
      title: "Build the pilot",
      objective: "Ship a thin, working AI agent on the chosen workflow.",
      actions: [
        "Define 5–10 representative input examples + expected outputs",
        "Wire LLM API with structured output schema",
        "Build a one-screen UI for the pilot user",
        "Add logging for every input/output",
      ],
      deliverable: "Working pilot used by one team member",
      estCost: 18000,
      owner: "Engineering",
      risks: ["Scope creep into nice-to-have features"],
    },
    {
      id: "p3",
      timeframe: "Month 2",
      title: "Measure & tune",
      objective: "Quantify time saved and quality vs baseline.",
      actions: [
        "Run pilot for 4 weeks with one user",
        "Compare against baseline weekly",
        "Tune prompts and add guardrails for failure modes",
        "Document what worked and what didn't",
      ],
      deliverable: "Pilot metrics report with go/no-go recommendation",
      estCost: 8000,
      owner: "Ops Lead + Engineering",
      risks: ["Hawthorne effect inflating early numbers"],
    },
    {
      id: "p4",
      timeframe: "Month 3",
      title: "Roll out to the team",
      objective: "Extend pilot to remaining team members with proper onboarding.",
      actions: [
        "Train each team member 1:1 (45 min sessions)",
        "Add monitoring dashboard for usage and errors",
        "Stand up a feedback channel for issues",
        "Lock in weekly metrics review",
      ],
      deliverable: "Full team using the tool, dashboard live",
      estCost: 12000,
      owner: "Ops Lead",
      risks: ["Adoption stalls; people revert to old workflow"],
    },
    {
      id: "p5",
      timeframe: "Month 4",
      title: "Harden for production",
      objective: "Make the system reliable enough to depend on.",
      actions: [
        "Add automated quality checks on AI outputs",
        "Set up alerting for error spikes or LLM outages",
        "Document runbooks for common failure modes",
        "Schedule monthly prompt review",
      ],
      deliverable: "On-call runbook + monitoring",
      estCost: 14000,
      owner: "Engineering",
      risks: ["Hidden long-tail failures that only surface at scale"],
    },
    {
      id: "p6",
      timeframe: "Month 6",
      title: "Scale to the next bottleneck",
      objective: "Apply the same playbook to the second-highest-friction workflow.",
      actions: [
        "Run bottleneck audit again on remaining workflows",
        "Pick next target and reuse pilot template",
        "Set ROI target before starting",
        "Plan headcount conversation with leadership",
      ],
      deliverable: "Pipeline of next 2–3 AI initiatives with projected ROI",
      estCost: 24000,
      owner: "Ops Lead",
      risks: ["Trying to scale before the first deployment is stable"],
    },
  ],
};
